language: node_js
node_js:
  - "10"
sudo: false
cache:
  npm: true
  directories:
    - node_modules
install: npm install
before_script:
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
script: npm run build
after_success:
  # Delete bucket content
  - aws_access_key_id=${AWS_ACCESS_KEY_ID} aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} aws s3 rm s3://sh.diogocardoso.me --recursive --region eu-west-2
deploy:
  provider: s3
  access_key_id:
    secure: p4yFCypkwZHdYzyrXsTD03OXnNAWl8AzgClieKVnr5MZF0E/SWrWd42RsHGD83ADGjxA9f72haNMBMSRGrDjuvsHO6xO4enKPKplaomEgZcv1RCnQXe1l5nuPp7DotyEiOFi9CVJIgYvWBYXHS94zORwGsVkTGWL0UnYR1XmTf3q+pd9VQMLVkl3vyKGuLgVFAtfUUhiX8Owq805BcLU7paVNBRT4ebBXMEY2ekb+ZO2YkZk1a3lybDgwYEmoJvu2UGsSmnGYsyGC+EFjBxekvEH0Cj1Z1n2QWpZLx7vJFVY5Dy1QYJ0S/7d6NechLercP4Uof4FvnPEf5X4yB29ppJjiduP5GyK8dgBpFgkv7lTxRWcxousoIPPiYAfeh5bJSeVNdaxtUVRHqt1Nx0fIQrCg6RQmsjs/FEEdvj/Tr3ghj9Me3JIH30WFWY9xUHeFR8of7Uw4JTh8kdZfLgYdqP70Ru/yAGiINQHi4u3j4bp7O1sXUKpJpdzjzg5wzrOLZtp8A5UXc7Isedkd/lixlLUq3yuSz9WUev/1ytXwSxTi3e2jILDuOF2kpZSgDFJ5EzjoWKGrBWdLLjBw6KQurENwN3MHigt6WD7Zzgr9H6hK9/AwY8SUwGBjApaFJzkXK5Ftqwrdniy5EnrvmKdnHjqtS22U1hC2N4u/hqd3bk=
  secret_access_key:
    secure: KBD7G0HyqvRErwTnyMtnCJEuS+SLeii6r71JTNKKLNuL+6UPq1rbF/u2VB5W0jiulcRAXCY6K9SOs52ktKFdf7yulxS91M2Pr/Vx7pfEYElLJLC6BInoJGtHQ2NXYFqZhq+DUc0e41KzmQPqbCCpzBOihRJWNyxkbvIKT7OuWHJLRLBL1f2YLl7xiVpXCSTQ5osyPJabANy5ViOVfK3WOud2cnWpudBvVSZyOHv+uM3OsBm63PUXqagf0FV+dBm6MhnH5OUel8ghhOuWdfJ8TDBGDQ3i2MSKypERhcsK/d5zcBQKZJr85pTLM519+rUHTcjmGitkbmCmlior55LnlWvSAPSKnJnZ+2JPkTGbcrclP0Qceq/VfEZ1Le+cZldzhYJvnrGC9RMHshFxx+IgG71TmA7aXy1iB46MjnRaAdDkwBSBu225Ls+KmLSyd2iPM4hhf2jczpld1cw44vI+ZRhpIiWl1t3bL5uGZT3cmQfFVsNd3sScRQYCH/G2ZJ+W3lG/GEn4cNt8GpVJzvmwvLXJ96YStnbtKmLV1hkTcCb+jhI/4tJVUN0pT4PmvzrMYWxlNc2mLZ4YbCFLQ0AuQrUSwGYZbgYC3HdQGX/beSKc+Ef6QxpZogFzHtF9UXZLN/SApgyV/bBgdwHAQjBJDqXNEn3DFNHVludN9oSRDQQ=
  bucket: blog.diogocardoso.me
  skip_cleanup: true
  region: eu-west-2
  local_dir: public
after_deploy:
  - aws_access_key_id=${AWS_ACCESS_KEY_ID} aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} --paths "/*"
notifications:
  email: false
env:
  global:
    # Cloudfront Distribution ID
    - secure: "SRDFTjCeQBWFIT4ow5YGwu5JS/ofb2ZDfdGSMvlsIx9FbsAqeM027GeSlzx9aPiPzD0WCo/tlmN96aA8gHBJ8B24eEtLDXxy1LCRrZwr7IxDI3YgRZs0xOMa/SHPBo+FzyFMHxA7fmI/FYb2AzvuCNq3/0BtCsXfEzvFBuKO9u1cbW58A6oJhONb83fwCtWtBHYzH2VapqCyp26seHOjGtoWkq7o9b/98uoOeO9PwvvaAIEvkbZHdr++5Rjay55gsr7KVZC1xBvuzkHC7x8o6qfYkMil8TCvCe4nla/raWpfaEP6TcfJZMFPyFPqPftSnbqOp5fh0nQG1V9e8HYZS3RNf84BDz+tDS5XGUGrd9Rhu1dd+4Skzdiouh0dUQ0uQfFKy+TUNJi6cWlAr+3OcyEA6XIM8idBJNO/4FiwoQCmB15755W1WZ9/l5HmONNX549i9zfuwd6FnZcFg+ILYgd+pW08v5oGFnPtUbum6MjJj7FQ6xikSElpDR2xtOTlU68hplzyi1qdfsvrEm6q0BngYjZKE3DwctfZHkmrOVoNzs1yQP7hxQh7Nk25dzsMgeNL2mAnQa+JSgpe2Q3jJ2v+1glAoDG9d/JMpHpdy1kj2pEOMQe5CyR+T/xTZrAkKab+ylrLD7MWY+IaMjpCklIhO0UgOlezUuTrqkS5hHc="
    # AWS Access Key ID
    - secure: "TviHmTMdvGlT8dR6pB8IlRnbDR2MhX3a1rfMRceyAc5JhwmYtDElaP82xheGlz1RN7IifEOGDJ7ho7CkJUNLdcgHhVktRIAni/yMcFbAyVJ5jwrdV63/qGOKtmBq/sXUHlQWiv02+2VboQ1keNQKxNL1dJMBiJeOIr186TcZgZJkQg21H/NvPiXjuo+bDJGtDBm3mnfPBtq6kjzvGdlAnwYi6Nl1UT/AlHN1Fe37Nj/KjQI5Rdj0d0QTEchzkfl4iSWR6TnTCD1BSsK5NkkfUOy+sWCA2NOOYnN917uHNGfaobK4oyw9pUU+fIsdFiMm9g5ZI6g+jH9a85kKYLQvk6gOJ5XEJZ5f8tKZzmq7LZo91T61YvetAHstjFYXCmdFVKiUL+NMBfFFmskbbc710L2edBzjCY5IIcZz/CRx4OlJo9xh93961h7I7WYmal2/fsgeASpZlYCxAiXAWm9lsxCqMZ3LamZ7xHLudr8xV8YJE4tm05m+i8XvnbBAhm/AcRzkw7QhLeG0KKwXnhjA+SmB1hHCY+IhF6Epajv4SO5cpy4sT+n307c+GED+6+lweyhnQuwqGnlnGS7yk9/ZGlpgdaI/KNlmrboW0i0zFaq4mJiq1Q8PjE3+dCrp3qGn51FHJf0fur29BAHv8efJkJeEv+Kc1eJY+O4oYU5xrKo="
    # AWS Secret Access Key
    - secure: "gLg+pK99FQp2iOHexD2YglRDrj1DXC/zMQ13t80X1L9h/MHizzB5VanbfIlIt9YWQYgovS4rZO4dT5o8qJk39skP4YRePIVCoc+Tpx/yks0Vojxml2m0LjhmNHuNG9Q4kRQzkRfai6ljUzOrn2541syLW8Yq5ZXmbGOikd0DZXyNrRuveV7HY49097LH2sYMQ6oWacjgSKky8a5rbReDNkme+NUxtD4+awQuikIy9Gn+budUcfyXy+vcMwR2cNid9Z36Xu0omfXddiJQh4BmAJPlwYP0cbMPtzXY0ZyZDS4H4rh3zdqm6Xpb9oGZeeywwVrhPbHfZX36qkgIibBftKC9kqGNfkPVic/YU1MCSV+9VDLi87VuQGO9JFillJvOn50hFriDc/b9qTa1UCEcAF6KvmIQzZSYpXqelM2CxtceqrLzNqSw540pPkpWn1aQJi6KzRUlLn4HzZ5ifOm+DqgD7q/kNVXiIug/u6iteHF973a9NKhFi5Knep6q5pAozs6pel0duJKyhh/JxesZCCIdl6KlQi7SlI8VM96rnn8VJZxI9Jk1pZfoPQrg2stOZs3grL3NCbsGQyTBrAOy75JzcgaJ/ARZEOaERG/iHAKHtXxYYyklrIVmnsNE3vP9SBPupixwsrzrQ27ko3pdAZRO7ZmJltkv2JrsPOb66/w="

